In [176]:
import numpy as np
import copy
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from numpy.random import *

In [453]:
def inputFieldData(text_path):
    f = open(text_path)
    line = f.readline()
    line_count = 1
    field_size = int(len(line) / 2)
    field = np.empty((0,field_size),int)
    agents_pos_list = [[-1,-1] for i in range(3)]
    while line:
        last_idx = line.find("\n")
        field_row = np.array([])
        for i in range(0,last_idx,2):
            field_row = np.append(field_row,int(line[i]))
#             if int(line[i]) % 2 == 0 and int(line[i]) != 0:
#                 agents_pos_list.append([line_count-1,int(i/2)])
            if int(line[i]) == 2:
                agents_pos_list[0] = [line_count-1,int(i/2)]
            elif int(line[i]) == 4:
                agents_pos_list[1] = [line_count-1,int(i/2)]
            elif int(line[i]) == 6:
                agents_pos_list[2] = [line_count-1,int(i/2)]
        field = np.append(field,np.array([field_row]),axis=0)
        line = f.readline()
        line_count += 1
    f.close()
    return field,agents_pos_list

In [604]:
# field,agents_pos_list = inputFieldData("multiAgentsField2.txt")
field,agents_pos_list = inputFieldData("test.txt")
print(field)
print("agents_pos_list = {0}".format(agents_pos_list))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  5.  0.  0.  0.  6.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  4.  0.  0.  1.  0.  1.]
 [ 1.  2.  0.  0.  7.  0.  0.  3.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
agents_pos_list = [[5, 1], [4, 3], [1, 5]]


In [605]:
field_row = len(field[0])
field_col = len(field)

In [606]:
alpha = 0.1
q_gamma = 0.9
now_pos_ground = 0

## aboutAction
action=0 : ↑
action=1 : →
action=2 : ↓
action=3 : ←

In [607]:
def jumpToNextPos(pos,action):
    if action == 0:
        next_pos = [pos[0]-1,pos[1]]
    elif action == 1:
        next_pos = [pos[0],pos[1]+1]
    elif action == 2:
        next_pos = [pos[0]+1,pos[1]]
    elif action== 3:
        next_pos = [pos[0],pos[1]-1]
    else:
        next_pos = [pos[0],pos[1]]
    return next_pos

In [608]:
def changeAction(idx,pos,next_poses,action,field):
    new_action = action
    for (i,next_pos) in enumerate(next_poses):
        if i == idx:
#             print("next_poses = {0}".format(next_poses))
            while field[next_poses[i][0],next_poses[i][1]] == 1:
                new_action = int(rand()*4)
                next_poses[i] = jumpToNextPos(pos,new_action)
        elif next_pos == next_poses[idx]: #他のエージェントが既に予約済みの場合
            while next_pos == next_poses[idx] or field[next_poses[idx][0],next_poses[idx][1]] == 1:
                new_action = int(rand()*4)
                next_poses[idx] = jumpToNextPos(pos,new_action)
#     print("pos = {0},new_action = {1}".format(pos,new_action))
    return new_actiont

In [619]:
def checkPosition(poses,actions,field):
    next_poses = []
    for i in range(len(poses)):
        pos = poses[i]
        action = actions[i]
        next_poses.append(jumpToNextPos(pos,action))
        
    for i in range(len(actions)):
        action = actions[i]
        pos = poses[i]
        next_pos = jumpToNextPos(pos,action)
        new_action = changeAction(i,pos,next_poses,action,field)        
        next_poses[i] = jumpToNextPos(pos,new_action)
#         next_pos = jumpToNextPos(pos,new_action)
        actions[i] = new_action
#     print("next_poses = {0}".format(next_poses))
    return actions

In [620]:
def buildNetwork(X_train,y_train):
    clf = MLPRegressor(solver="adam",random_state=1,max_iter=1000,hidden_layer_sizes=(20,50,10))
    print("X_train.shape = {0},y_train.shape={1}".format(X_train.shape,y_train.shape))
#     print("y_train={0}".format(y_train))
    clf.fit(X_train,y_train)
    return clf

In [621]:
def initNetwork(field):
    X_train = np.asarray([field])
    X_train = X_train.reshape(1,field_row*field_col)
    y_train = np.array([[0,0]])
    clf = buildNetwork(X_train,y_train)
    return clf

In [622]:
def predictActions(clf,field):
    X_test = np.asarray(field).reshape(1,field_row*field_col)
    actions = clf.predict(X_test)[0]
    for i in range(len(actions)):
        actions[i] = int(actions[i])
#     print("actions = {0}".format(actions))
    if rand() < 0.4:
#         idx = int(len(actions) * rand())
#         actions[idx] = int((actions[idx] + rand() * 3 + 1)) % 4
        for i in range(len(actions)):
            actions[i] = int(actions[i] + rand() * 3 + 1) % 4
    return actions

In [623]:
def updateField(poses,next_poses,field):
    goal_flags = [False for i in range(len(poses))]
    for i in range(len(agents_pos_list)):
        pos = poses[i]
        next_pos = next_poses[i]
        if pos != next_pos:
            if field[pos[0],pos[1]] % 2 == 0:
                field[pos[0],pos[1]] = 0
        if field[next_pos[0],next_pos[1]] == 3 and i == 0 :
            goal_flags[0] = True
        elif field[next_pos[0],next_pos[1]] == 5 and i == 1:
            goal_flags[1] = True
        elif field[next_pos[0],next_pos[1]] == 7 and i == 2:
            goal_flags[2] = True
        
        if goal_flags[i] == False:
            if i == 0 and field[next_pos[0],next_pos[1]] != 5 and field[next_pos[0],next_pos[1]] != 7:
                field[next_pos[0],next_pos[1]] = 2
            elif i == 1 and field[next_pos[0],next_pos[1]] != 3 and field[next_pos[0],next_pos[1]] != 7:
                field[next_pos[0],next_pos[1]] = 4
            elif i == 2 and field[next_pos[0],next_pos[1]] != 3 and field[next_pos[0],next_pos[1]] != 5:
                field[next_pos[0],next_pos[1]] = 6
    
    return goal_flags

In [624]:
def createTrainData(init_poses,field,clf=None):
    createFlag = False
    field_data = [copy.deepcopy(field)]
    action_data = []
    poses = init_poses
    goal_flags = [False for i in range(len(poses))]
    for i in range(FIND_ROOT_MAX_LOOP):
        if clf != None:
            pred_actions = predictActions(clf,field)
        else:
            pred_actions = [int(rand()*4) for i in range(3)]
        actions = checkPosition(poses,pred_actions,field)
        for (j,goal_flag) in enumerate(goal_flags):
            if goal_flag:
                actions[j] = 4
        action_data.append(actions)
        next_poses = []
        for j in range(len(agents_pos_list)):
            pos = poses[j]
            action = actions[j]
            next_poses.append(jumpToNextPos(pos,action))
        goal_flags = updateField(poses,next_poses,field)

        if goal_flags[0] and goal_flags[1] and goal_flags[2]:
            field_data.append(copy.deepcopy(field))
            action_data.append([4,4,4])
#             printFieldData(field_data,action_data)
            createFlag = True
            break
        field_data.append(copy.deepcopy(field))
        poses = next_poses
    return field_data,action_data,createFlag,next_poses

In [625]:
def printFieldData(field_data,action_data):
    print("------------------------------------------------")
    for i in range(len(field_data)):
        print(field_data[i])
        print(action_data[i])
    print("------------------------------------------------")

In [629]:
FIND_ROOT_MAX_LOOP = 50
def runningCreatePath(init_field,agents_pos_list):
    clf = None
    path_count = 1e+7
    pathes = []
    success_field_data = []
    last_poses = []
    success_last_poses = []
    for i in range(2000):
        createFlag = False
        field = copy.deepcopy(init_field)
        if (i+1) % 100 == 0:
            print("epoch = {0}".format(i+1))
        field_data,action_data,createFlag,last_poses = createTrainData(agents_pos_list,field,clf)
        if createFlag:
            np_field_data = np.asarray(field_data)
            np_action_data = np.asarray(action_data)
            if path_count >np_field_data.shape[0]:
                path_count = np_field_data.shape[0]
                clf = buildNetwork(np_field_data.reshape(np_field_data.shape[0],np_field_data.shape[1]*np_field_data.shape[2]),np_action_data)
                pathes.append(action_data)
                printFieldData(field_data,action_data)
                success_field_data = copy.deepcopy(field_data)
                success_last_poses = copy.deepcopy(last_poses)
    return success_field_data,success_last_poses

In [630]:
def updateAndWriteField(new_field):
    f = open('test.txt','w')
    for i in range(len(new_field)):
        for j in range(len(new_field[0])):
            letter = str(int(new_field[i][j]))
            if j != len(new_field[0]) - 1:
                letter += ","
            else:
                letter += "\n"
            f.write(letter)
    f.close()

In [631]:
# field,agents_pos_list = inputFieldData("multiAgentsField2.txt")
field,agents_pos_list = inputFieldData("test.txt")
for i in range(3):
    success_field_data,success_last_poses = runningCreatePath(field,agents_pos_list)
    new_field = copy.deepcopy(success_field_data[-1])
    for j in range(len(success_last_poses)):
        pos = success_last_poses[j]
        new_field[pos[0],pos[1]] = j*2 + 2
        agents_pos_list[j] = pos
        goal_pos = [int(rand()*7),int(rand()*7)]
        while new_field[goal_pos[0],goal_pos[1]] != 0:
            goal_pos = [int(rand()*7),int(rand()*7)]
        new_field[goal_pos[0],goal_pos[1]] = j*2 + 3
    updateAndWriteField(new_field)
    field,agents_pos_list = inputFieldData("test.txt")

X_train.shape = (37, 63),y_train.shape=(37, 3)
------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  2.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  4.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[1, 3, 2]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  2.  0.  0.  3.  0.  1.]
 [ 1.  6.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  4.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[1, 3, 0]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  0.  0.  2.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  4.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[1, 3, 2]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.

------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  2.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  4.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 3.  3.  1.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  6.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  4.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 2.  1.  3.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  0.  0.  0.  0.  3.  0.  1.]
 [ 1.  2.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  4.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 0.  3.  1.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  6.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.

[ 4.  2.  4.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  4.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 4.  3.  4.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[4, 4, 4]
------------------------------------------------
epoch = 300
epoch = 400
X_train.shape = (14, 63),y_train.shape=(14, 3)
------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  2.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  4.  0.  1.]
 [ 1.  1.  

epoch = 1000
epoch = 1100
epoch = 1200
epoch = 1300
epoch = 1400
epoch = 1500
epoch = 1600
epoch = 1700
epoch = 1800
epoch = 1900
X_train.shape = (9, 63),y_train.shape=(9, 3)
------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  2.  0.  0.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  4.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 1.  1.  2.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  2.  0.  0.  3.  0.  1.]
 [ 1.  6.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  7.  5.  0.  0.  0.  0.  4.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 1.  3.  2.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  2.  0.  3.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  6.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.

------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  2.  0.  1.]
 [ 1.  0.  1.  3.  1.  5.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  6.  4.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 2.  1.  0.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  1.  3.  1.  5.  2.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  6.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  4.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 0.  1.  2.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  2.  0.  1.]
 [ 1.  0.  1.  3.  1.  5.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  6.  0.  0.  4.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 1.  1.  0.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  0.  2.  1.]
 [ 1.  0.

epoch = 1200
epoch = 1300
epoch = 1400
epoch = 1500
epoch = 1600
X_train.shape = (12, 63),y_train.shape=(12, 3)
------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  2.  0.  1.]
 [ 1.  0.  1.  3.  1.  5.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  6.  4.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 2.  1.  1.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  1.  3.  1.  5.  2.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  0.  6.  4.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 0.  1.  5.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  7.  0.  0.  0.  2.  0.  1.]
 [ 1.  0.  1.  3.  1.  5.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  0.  6.  0.  4.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  6.  0.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  7.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  4.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[4, 1, 1]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  6.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  7.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  4.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[4, 3, 1]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  7.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  4.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[4, 3, 2]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.  1.  6.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  

------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  6.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.  1.  2.  1.  4.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  7.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 2.  0.  1.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  2.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  7.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 2.  3.  2.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  5.  4.  3.  0.  0.  1.]
 [ 1.  0.  1.  6.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  7.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[ 1.  3.  2.]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  5.  0.  3.  0.  0.  1.]
 [ 1.  0.

In [587]:
for i in range(len(pathes[-1])):
    print(pathes[-1][i])

[ 3.  0.  1.]
[ 3.  2.  0.]
[ 3.  0.  4.]
[ 2.  1.  4.]
[ 0.  1.  4.]
[ 2.  1.  4.]
[ 0.  2.  4.]
[ 3.  2.  4.]
[ 2.  2.  4.]
[ 2.  4.  4.]
[4, 4, 4]


In [586]:
print(success_field_data[-1])

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  7.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  1.]
 [ 1.  0.  1.  1.  0.  0.  1.]
 [ 1.  0.  3.  0.  0.  5.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [263]:
print(success_last_poses)

[[2, 2], [1, 5], [5, 1]]


In [414]:
new_field = copy.deepcopy(success_field_data[-1])
for i in range(len(success_last_poses)):
    pos = success_last_poses[i]
    new_field[pos[0],pos[1]] = i*2 + 2
    agents_pos_list[i] = pos
for i in range(len(agents_pos_list)):
    goal_pos = [int(rand()*7),int(rand()*7)]
    while new_field[goal_pos[0],goal_pos[1]] != 0:
        goal_pos = [int(rand()*7),int(rand()*7)]
    new_field[goal_pos[0],goal_pos[1]] = i*2 + 3
print(new_field)

IndexError: list index out of range

In [285]:
f = open('test.txt','w')
for i in range(len(new_field)):
    for j in range(len(new_field[0])):
        letter = str(int(new_field[i][j]))
        if j != len(new_field[0]) - 1:
            letter += ","
        else:
            letter += "\n"
        f.write(letter)
f.close()

In [284]:
FIND_ROOT_MAX_LOOP = 100
field,agents_pos_list = inputFieldData("test.txt")
print("init_field = \n{0}".format(field))
clf = None
path_count = 1e+7
pathes = []
success_field_data = []
last_poses = []
success_last_poses = []
for i in range(500):
    createFlag = False
    field,agents_pos_list = inputFieldData("test.txt")
    if (i+1) % 100 == 0:
        print("epoch = {0}".format(i+1))
    if clf == None:
        field_data,action_data,createFlag,last_poses = createTrainData(agents_pos_list,field)
    else:
        field_data,action_data,createFlag,last_poses = createTrainData(agents_pos_list,field,clf)
    if createFlag:
        np_field_data = np.asarray(field_data)
        np_action_data = np.asarray(action_data)
        if path_count > np_field_data.shape[0]:
            path_count = np_field_data.shape[0]
            clf = buildNetwork(np_field_data.reshape(np_field_data.shape[0],np_field_data.shape[1]*np_field_data.shape[2]),np_action_data)
            pathes.append(action_data)
            printFieldData(field_data,action_data)
            success_field_data = copy.deepcopy(field_data)
            success_last_poses = copy.deepcopy(last_poses)

init_field = 
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  4.  1.]
 [ 1.  0.  2.  1.  0.  0.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  6.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
X_train.shape = (22, 49),y_train.shape=(22, 3)
------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  4.  1.]
 [ 1.  0.  2.  1.  0.  0.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  6.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
[2, 0, 1]
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  4.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  2.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  0.  6.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
[3, 3, 0]
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  4.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  2.  0.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]

------------------------------------------------
epoch = 100
X_train.shape = (13, 49),y_train.shape=(13, 3)
------------------------------------------------
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  4.  1.]
 [ 1.  0.  2.  1.  0.  0.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  6.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
[ 2.  0.  1.]
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  4.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  2.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  0.  6.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
[ 0.  3.  0.]
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  4.  0.  0.  0.  2.  1.]
 [ 1.  0.  0.  1.  0.  0.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  5.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]
[ 2.  1.  4.]
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  4.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  2.  1.]
 [ 1.  3.  1.  1.  0.  0.  1.]
 [ 1.  0.  7.  0.  0.  