In [189]:
import numpy as np
from numpy.random import *

In [186]:
def inputFieldData(text_path):
    f = open(text_path)
    line = f.readline()
    line_count = 1
    field_size = int(len(line) / 2)
    field = np.empty((0,field_size),int)
    while line:
        last_idx = line.find("\n")
        field_row = np.array([])
        for i in range(0,last_idx,2):
            field_row = np.append(field_row,int(line[i]))
        field = np.append(field,np.array([field_row]),axis=0)
        line = f.readline()
        line_count += 1
    f.close()
    return field

In [188]:
field = inputFieldData("singleAgentField.txt")
print(field)
agent_pos_list = [[5,1],[1,1]]
goal_pos_list = [[1,5],[5,5]]

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [191]:
def checkState(pos,action):
    if action == 0 and field[pos[0]-1,pos[1]] == 1:
        return False
    elif action == 1and field[pos[0],pos[1]+1] == 1:
        return False
    elif action == 2 and field[pos[0]+1,pos[1]] == 1:
        return False
    elif action == 3 and field[pos[0],pos[1]-1] == 1:
        return False
    else:
        return True

In [193]:
def selectAction(pos):
    action = int(rand() * 4)
    while checkState(pos,action) == False:
        action = int(rand() * 4)
    return action

In [ ]:
def createPath(start_pos,goal_pos):
    pos = start_pos
    action = selectAction(pos)
    