In [2]:
import numpy as np
from numpy.random import *

In [41]:
def inputFieldData(text_path):
    f = open(text_path)
    line = f.readline()
    line_count = 1
    field_size = int(len(line) / 2)
    field = np.empty((0,field_size),int)
    agents_pos_list = []
    while line:
        last_idx = line.find("\n")
        field_row = np.array([])
        for i in range(0,last_idx,2):
            field_row = np.append(field_row,int(line[i]))
            if int(line[i]) == 2:
                agents_pos_list.append([line_count-1,int(i/2)])
        field = np.append(field,np.array([field_row]),axis=0)
        line = f.readline()
        line_count += 1
    f.close()
    return field,agents_pos_list

In [42]:
field,agents_pos_list = inputFieldData("singleAgentField2.txt")
print(field)
print("agents_pos_list = {0}".format(agents_pos_list))

[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  1.  3.  1.]
 [ 1.  0.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  2.  1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  1.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
agents_pos_list = [[5, 2]]


In [31]:
field_row = len(field[0])
field_col = len(field)
q = np.zeros((field_col,field_row,4))
reward = np.zeros((field_col,field_row))
for i in range(field_row):
    for j in range(field_col):
        if field[i][j] == 1:
            reward[i][j] = -100
        elif field[i][j] == 3:
            reward[i][j] = 10

In [32]:
alpha = 0.1
q_gamma = 0.9

## aboutAction
action=0 : ↑
action=1 : →
action=2 : ↓
action=3 : ←

In [33]:
def jumpToNextPos(pos,action):
    if action == 0:
        next_pos = [pos[0]-1,pos[1]]
    elif action == 1:
        next_pos = [pos[0],pos[1]+1]
    elif action == 2:
        next_pos = [pos[0]+1,pos[1]]
    else:
        next_pos = [pos[0],pos[1]-1]
    return next_pos

In [34]:
def selectMaxActionQValue(pos):
    return np.max(q[pos[0]][pos[1]])

In [35]:
def selectAction(pos,test=False):
    action = np.argmax(q[pos[0],pos[1]])
#     print("pos = {0},action={1}".format(pos,action))
    if test:
        return action
    if rand() <= 0.3:
        action = int((action + rand() * 3 + 1)) % 4
    return action

In [36]:
def checkPosition(pos,next_pos,action):
    if next_pos[0] < 0 or next_pos[0] >= field_col or next_pos[1] < 0 or next_pos[1] >= field_row:
        q[pos[0]][pos[1]][action] = -100
        return True
    else:
        return False

In [38]:
for j in range(10000):
    init_pos = [5,2]
    pos = init_pos
    for i in range(100):
        action = selectAction(pos)
        next_pos = updateQValue(pos,action)
        pos = next_pos
print(q)

[[[-100.          -81.53618148  -81.54224498 -100.        ]
  [-100.          -79.55390124   20.39055205 -171.91346145]
  [-100.          -77.24131197   22.65616895  -81.61726809]
  [-100.          -74.81829984   25.17352105  -79.60458631]
  [-100.         -147.36841911   27.97057895  -77.34383103]
  [-100.          -52.63157895  -52.63157895  -74.82647895]
  [-100.         -147.36842105   52.63157895 -147.36842105]
  [-100.         -100.          -52.63157895  -52.63157895]]

 [[-172.82505894   20.39055205  -83.24368793 -100.        ]
  [ -81.64850315   22.65616895   18.35149685  -81.64850315]
  [ -79.60944795   25.17352105   20.39055205   20.39055205]
  [ -77.34383105   27.97057895  -72.02942105   22.65616895]
  [ -74.82647895  -52.63157895   31.07842105   25.17352105]
  [-147.36842105   52.63157895  -57.36842105   27.97057895]
  [ -52.63157895  -52.63157895   47.36842105  -52.63157895]
  [-147.36842105 -100.          -57.36842105   52.63157895]]

 [[ -81.16742581   18.35149685  -85.

In [39]:
def createPath(init_pos):
    print(init_pos)
    pos = init_pos
    while field[pos[0],pos[1]] != 3:
        action = selectAction(pos,test=True)
        next_pos = jumpToNextPos(pos,action)
        pos = next_pos
        print(pos)

In [40]:
init_pos = [5,2]
createPath(init_pos)

[5, 2]
[6, 2]
[6, 3]
[6, 4]
[5, 4]
[4, 4]
[3, 4]
[3, 5]
[3, 6]
[2, 6]
[1, 6]
